version: "3"

vars:
  PYTHON: uv run python
  MKDOCS: uv run mkdocs
  PORT: 8001

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:
    desc: Install dependencies using uv
    cmds:
      - uv sync

  serve:
    desc: Run local MkDocs dev server
    deps: [build]
    cmds:
      - "{{.MKDOCS}} serve -a 127.0.0.1:{{.PORT}}"

  build:
    desc: Build static site (like CI)
    cmds:
      - "{{.PYTHON}} scripts/build.py"

  clean:
    desc: Remove generated artifacts
    cmds:
      - rm -rf .work site/projects public

  rebuild:
    desc: Clean, fetch, and build from scratch
    cmds:
      - task clean
      - task build

  ci:
    desc: Run the same steps as GitHub Actions
    cmds:
      - task install
      - task rebuild

  dump_code:
    desc: Dump relevant codebase
    cmds:
      - "{{.PYTHON}} scripts/dump_source.py"

  generate_ontology_docs:
    desc: Generate ontology docs
    cmds:
      - "{{.PYTHON}} scripts/generate_ontology_docs.py /home/lspxl/git/github.com/celine-eu/celine-eu.github.io/site/ontologies/celine.ttl /home/lspxl/git/github.com/celine-eu/celine-eu.github.io/site/ontologies/celine https://celine-eu.github.io/ontologies/celine#"
